from enum import Enum


class ComplaintStatus(str, Enum):
    DRAFT = "DRAFT"
    PENDING_TRIAGE = "PENDING_TRIAGE"
    AWAITING_INFORMATION = "AWAITING_INFORMATION"
    UNDER_QA_REVIEW = "UNDER_QA_REVIEW"
    UNDER_INVESTIGATION = "UNDER_INVESTIGATION"
    COMMITTED = "COMMITTED"
    CLOSED = "CLOSED"
    CANCELLED = "CANCELLED"


class ProductType(str, Enum):
    API = "API"
    FDF = "FDF"
    UNKNOWN = "UNKNOWN"


class Severity(str, Enum):
    CRITICAL = "CRITICAL"
    MAJOR = "MAJOR"
    MINOR = "MINOR"
    UNDETERMINED = "UNDETERMINED"


class Priority(str, Enum):
    IMMEDIATE = "IMMEDIATE"
    HIGH = "HIGH"
    NORMAL = "NORMAL"
    LOW = "LOW"
    UNDETERMINED = "UNDETERMINED"


class EvidenceType(str, Enum):
    USER_TEXT = "USER_TEXT"
    USER_CORRECTION = "USER_CORRECTION"
    PDF = "PDF"
    DOCX = "DOCX"
    EMAIL = "EMAIL"
    IMAGE = "IMAGE"
    SYSTEM_RECORD = "SYSTEM_RECORD"
    AI_INFERENCE = "AI_INFERENCE"


class ActorType(str, Enum):
    USER = "USER"
    AI_AGENT = "AI_AGENT"
    SYSTEM = "SYSTEM"


class MessageRole(str, Enum):
    USER = "USER"
    ASSISTANT = "ASSISTANT"
    SYSTEM = "SYSTEM"
    TOOL = "TOOL"


class ExtractionStatus(str, Enum):
    PENDING = "PENDING"
    VALIDATING = "VALIDATING"
    EXTRACTING = "EXTRACTING"
    COMPLETE = "COMPLETE"
    FAILED = "FAILED"


class SafetyRoute(str, Enum):
    PRODUCT_QUALITY = "PRODUCT_QUALITY"
    POSSIBLE_ADVERSE_EVENT = "POSSIBLE_ADVERSE_EVENT"
    QUALITY_AND_ADVERSE_EVENT = "QUALITY_AND_ADVERSE_EVENT"
    COUNTERFEIT_OR_TAMPERING = "COUNTERFEIT_OR_TAMPERING"
    DISTRIBUTION_OR_STORAGE = "DISTRIBUTION_OR_STORAGE"
    SERVICE_ONLY = "SERVICE_ONLY"
    UNDETERMINED = "UNDETERMINED"


class RecordSource(str, Enum):
    MANUAL_DEMO_SEED = "MANUAL_DEMO_SEED"
    USER_MESSAGE = "USER_MESSAGE"
    USER_UPLOAD = "USER_UPLOAD"
    AI_EXTRACTION = "AI_EXTRACTION"
    SYSTEM_INTEGRATION = "SYSTEM_INTEGRATION"
